//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliGarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionType
    {
        public ActionType()
        {
            this.RecordActions = new HashSet<RecordAction>();
        }
    
        public decimal IdAction { get; set; }
        public string ActionName { get; set; }
    
        public virtual ICollection<RecordAction> RecordActions { get; set; }
    }
}
