//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliGarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public decimal IdProfile { get; set; }
        public string ProfileName { get; set; }
        public double TemperatureStandard { get; set; }
        public double LightStandard { get; set; }
        public double HumidityStandard { get; set; }
        public double WaterDuration { get; set; }
    }
}
