//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliGarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordAction
    {
        public decimal IdRecordAction { get; set; }
        public decimal IdAction { get; set; }
        public double Duration { get; set; }
    
        public virtual ActionType ActionType { get; set; }
    }
}
