//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliGarAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordSituation
    {
        public decimal IdRecordSituation { get; set; }
        public System.DateTime RecordTime { get; set; }
        public double Temperature { get; set; }
        public double Light { get; set; }
        public double Humidity { get; set; }
    }
}
